### ISSUE TITLE
defalias 't overwrites self-insert-command

### ISSUE THREAD

**Issue by TLINDEN** [alphapapa/outshine#22] opened 2018-10-08 17:42 UTC
Given the following bare config file:
```
(add-hook 'emacs-lisp-mode-hook
          (lambda()
            (outline-minor-mode)
            (outshine-hook-function)))


(eval-after-load "outline"
  '(progn
     (add-hook 'outline-minor-mode-hook
               (lambda ()
                 (setq outshine-use-speed-commands t
                       )))))

(defun tell ()
  (interactive)
  (message "here"))

(defalias 't 'tell)
```

and starting emacs with:
```
emacs -L outshine -L . -l ../test.el -Q
```

where `test.el` is a file containing the above snippet, and `outshine` contains the git repo of the latest outshine from [here](https://github.com/thblt/outshine/tree/leave-outline-alone) as suggested [here](https://www.reddit.com/r/emacs/comments/9hpkfr/outshine_users_big_changes_ahead_some_testing/), the following happens: upon entering `emacs-lisp-mode` hitting any key (besides controll key sequences) executes the `(here)` function (it prints a "here" in the `*Messages*` buffer per key pressed).

If you're asking why one would create an alias `t`: [I created a hydra for org tables and wanted to have a short shortcut](https://github.com/abo-abo/hydra/issues/300).

However - the effect also happens with an older outshine version (version 2.0). I also doesn't happen when `outshine-use-speed-commands` is disabled. The effect is not limited to outshine inside emacs-lisp-mode, but happens with any mode as long as outshine and speed commands are enabled.

My emacs version is:
GNU Emacs 25.3.2 (x86_64-pc-linux-gnu, GTK+ Version 3.10.8) of 2018-10-02

best,
Tom

**Comment by alphapapa** [comment] 2018-10-08 22:41
Sorry, I don't see what the bug is here. You know that t is a reserved
symbol in lisp, right? I don't know if defining a function t would work,
even though elisp is a lisp-2. If it does, it's probably not a good idea.
And outshine has nothing to do with hydra.  If you're trying to control key
bindings in a hydra, you're going about it the wrong way.

**Comment by alphapapa** [comment] 2018-10-09 02:55
The problem is probably somewhere in `outshine-self-insert-command`.  But I think this is a case of, "It hurts when I do that," "So don't do that."  ;)  It's not a good idea to use `t` as a function name in lisp.  Even if it might technically be a minor bug in Outshine that this happens, or at least a suboptimal behavior, I don't think this is something that needs to be fixed in Outshine.  I imagine that there are many other cases in which a function `t` would cause problems and strange behavior.

I don't even understand why you would do this.  Key bindings are unrelated to function names.  You don't need to name a function `t` in order to access it by pressing `t`.

**Closed** 2018-10-09 06:27 UTC
